steps:
  - label: ":demo: Demo"
    name: "demo"
    command: echo "Buildkite demo"

  - label: ":demo: Demo using make and docker-compose"
    name: "demo-make-docker-compose"
    command: make demo-make-docker-compose

#  - label: ":ansible: Demo"
#    name: "ansible-demo"
#    command: ansible localhost -m setup
